language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  # cython
  - pip install cython
  # ODE
  - wget https://downloads.sourceforge.net/project/opende/ODE/0.13/ode-0.13.tar.bz2
  - tar -xvf ode-0.13.tar.bz2
  - cd ode-0.13
  - ./configure CFLAGS="$CFLAGS -fPIC" CXXFLAGS="$CXXFLAGS -fPIC"
  - make
  - sudo make install
  - cd ..
  # py3ode
  - pip install .
# command to run tests
script: pytest
